== Allgemeines
=== rechtliche Grundlagen
//Todo Links und Anhänge definieren 
Seit dem 1. Juli 2008 ist das https://www.fedlex.admin.ch/eli/cc/2008/388/de[Bundesgesetz über Geoinformation (GeoIG, SR 510.62)] in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des https://www.sz.ch/public/upload/assets/48275/214_110.pdf?fp=2[kantonalen Geoinformationsgesetzes (KGeoiG, SRSZ 214.110)]. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die https://www.sz.ch/public/upload/assets/5600/214_111.pdf?fp=11[kantonale Verordnung über Geoinformation (KGeoiV, SRSZ 214.111)] in Kraft. Sie präzisiert das KGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.


===  Zweck des Dokuments
Dieses Dokument beschreibt den Geobasisdatensatz
 
* *__<Name des Datensatzes>__.* +

__<weitere Beschreibungen>__ +

Der Geobasisdatensatz ist Bestandteil des ÖREB-Katasters. +

Diese Dokumentation richtet sich an alle Personen, welche sich über dieses Thema informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
